// Code generated by MockGen. DO NOT EDIT.
// Source: databasemigration.go
//
// Generated by this command:
//
//	mockgen -source=databasemigration.go -package=databasemigration -destination=./mock/databasemigration.go
//

// Package databasemigration is a generated GoMock package.
package databasemigration

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// MigrateClickHouse mocks base method.
func (m *MockRepository) MigrateClickHouse(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MigrateClickHouse", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// MigrateClickHouse indicates an expected call of MigrateClickHouse.
func (mr *MockRepositoryMockRecorder) MigrateClickHouse(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MigrateClickHouse", reflect.TypeOf((*MockRepository)(nil).MigrateClickHouse), ctx)
}

// MigratePostgres mocks base method.
func (m *MockRepository) MigratePostgres(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MigratePostgres", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// MigratePostgres indicates an expected call of MigratePostgres.
func (mr *MockRepositoryMockRecorder) MigratePostgres(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MigratePostgres", reflect.TypeOf((*MockRepository)(nil).MigratePostgres), ctx)
}
