// Code generated by MockGen. DO NOT EDIT.
// Source: notifications.go
//
// Generated by this command:
//
//	mockgen -source=notifications.go -package=notifications -destination=./mock/notifications.go
//

// Package notifications is a generated GoMock package.
package notifications

import (
	context "context"
	reflect "reflect"

	notifications "github.com/hitesh22rana/chronoverse/internal/model/notifications"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateNotification mocks base method.
func (m *MockRepository) CreateNotification(ctx context.Context, userID, kind, payload string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNotification", ctx, userID, kind, payload)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNotification indicates an expected call of CreateNotification.
func (mr *MockRepositoryMockRecorder) CreateNotification(ctx, userID, kind, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNotification", reflect.TypeOf((*MockRepository)(nil).CreateNotification), ctx, userID, kind, payload)
}

// ListNotifications mocks base method.
func (m *MockRepository) ListNotifications(ctx context.Context, userID, cursor string) (*notifications.ListNotificationsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNotifications", ctx, userID, cursor)
	ret0, _ := ret[0].(*notifications.ListNotificationsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNotifications indicates an expected call of ListNotifications.
func (mr *MockRepositoryMockRecorder) ListNotifications(ctx, userID, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNotifications", reflect.TypeOf((*MockRepository)(nil).ListNotifications), ctx, userID, cursor)
}

// MarkNotificationsRead mocks base method.
func (m *MockRepository) MarkNotificationsRead(ctx context.Context, notificationIDs []string, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkNotificationsRead", ctx, notificationIDs, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkNotificationsRead indicates an expected call of MarkNotificationsRead.
func (mr *MockRepositoryMockRecorder) MarkNotificationsRead(ctx, notificationIDs, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkNotificationsRead", reflect.TypeOf((*MockRepository)(nil).MarkNotificationsRead), ctx, notificationIDs, userID)
}
